### PR TITLE
Updated Set-RscSla to retain existing values for non-provided fields

### PR DESCRIPTION
**Pull request by lokirubrik**
# Summary:
-> Fetches existing SLA values from the Sla input
    parameter or via pipeline support, making the
    Sla parameter mandatory.
-> Enhances support to set all SLA fields not
    provided as parameters to their existing
    values.
-> Removes the Id parameter.

# Test Plan:
-> Conducted manual testing by invoking Set-RscSla
for various scenarios and ensured that all
non-provided fields are set to their
existing values.

Testing Doc: [link](https://docs.google.com/document/d/1iNpeQWo0M9zKDplz88w9O11Y8FnIUzZU7-EiziUYQm8/edit?tab=t.0#heading=h.yjl3kf4q6btx)

-> Written e2e test for the setRscSla script. 
Successfully executed in 'dev' and 
'staging' environments.

# JIRA:
SPARK-330821

# Revert Plan:
NA

### CODE REVIEW

**Review by jakerobinson — COMMENTED** [review]
we're going to need some robust testing for this. How can we be sure that when a user updates an SLA, we didn't miss any settings?

**Comment by jakerobinson** [comment]
@lokirubrik Yeah, I mean an actual test in toolkit/tests/e2e/Set-RscSla.Tests.ps1

**Comment by lokirubrik** [comment]
> @lokirubrik Yeah, I mean an actual test in toolkit/tests/e2e/Set-RscSla.Tests.ps1

Sure, working on it.

**Comment by jakerobinson** [comment]
LGTM!

**Comment by lokirubrik** [comment]
> > @lokirubrik Yeah, I mean an actual test in toolkit/tests/e2e/Set-RscSla.Tests.ps1
> 
> Added e2e for Set-RscSla

**Note:** Have tested the script by running it over all the existing sla on `ui.dev` and `manualtest` environment. While testing for several SLAs the script failed, which ideally shouldn’t happen as the script was simply patching all the fields it got from the get request, without modifying them. Collected all the unique failures and discussed them with DLC and Archival Team, slack discussion thread can be found [here](https://rubrikinc.slack.com/archives/C02SMHETWQM/p1731601536796089) . The failures were simply happening becuase those SLA were very old, created before 2022, when the major archival revamp happened, also for some of the SLAs, archival locations was deleted which led to returning missing archival-Ids, hence patching them caused failure.

**Review by guirava — APPROVED** [review]

**Pull request merged**
